-- Query Final: Posição Retroativa RESUMIDA (para o main.py)
WITH dados_base AS (
    SELECT
        CODICLIE AS cod_cliente,
        NOMECLIE AS cliente,
        CPF_CNPJ AS documento_cliente,
        UF_CLIENTE AS uf_cliente,
        DOCUMENTO,
        PARCELA,
        DATAEMIS,
        VALOR_NA_DATA AS vlr_total_vencidos,
        VALOR_TITULO AS vlr_totalcompras,
        FORMPAG
    FROM (
    -- Início da nossa query analítica detalhada (usada como fonte de dados)
    SELECT
        CAST(CRECCLIE AS VARCHAR) as CODICLIE,
        CAST(clie.CADANOME AS VARCHAR) as NOMECLIE,
        CAST(clie.CADACNPJ AS VARCHAR) as CPF_CNPJ,
        CAST(TRIM(clie.CADAESTA) AS VARCHAR) as UF_CLIENTE,
        CONCAT(CRECDOCU, '-P', CRECPARC) as DOCUMENTO,
        CRECPARC as PARCELA,
        CAST(CRECVALO AS NUMERIC(15,2)) as VALOR_TITULO,
        CAST(CRECVALO AS NUMERIC(15,2)) as VALOR_NA_DATA,
        CAST(CASE WHEN CRECFNOT <> ' ' THEN CRECFNOT ELSE CRECTPDC END AS VARCHAR) as FORMPAG,
        CRECEMIS as DATAEMIS
    FROM ARQCREC
    LEFT JOIN ARQCADA as clie ON clie.CADACODI = CRECCLIE
    LEFT JOIN ARQCLIE ON CLIECODI = CRECCLIE
    WHERE CRECEMIS <= %s AND CRECCARD = 0

    UNION ALL

    SELECT
        CAST(BRECCLIE AS VARCHAR) as CODICLIE,
        CAST(clie.CADANOME AS VARCHAR) as NOMECLIE,
        CAST(clie.CADACNPJ AS VARCHAR) as CPF_CNPJ,
        CAST(TRIM(clie.CADAESTA) AS VARCHAR) as UF_CLIENTE,
        CONCAT(BRECDOCU, '-P', BRECPARC) as DOCUMENTO,
        BRECPARC as PARCELA,
        CAST(BRECVBAX + BRECVTAN AS NUMERIC(15,2)) as VALOR_TITULO,
        CAST(BRECVBAX + BRECVTAN AS NUMERIC(15,2)) as VALOR_NA_DATA,
        CAST(CASE WHEN BRECFNOT <> '' THEN BRECFNOT ELSE BRECTPDC END AS VARCHAR) as FORMPAG,
        BRECEMIS as DATAEMIS
    FROM ARQBREC
    LEFT JOIN ARQCADA as clie ON clie.CADACODI = BRECCLIE
    LEFT JOIN ARQCLIE ON CLIECODI = BRECCLIE
    WHERE BRECEMIS <= %s AND BRECDPAG > %s AND BRECCARD = 0

    UNION ALL

    SELECT
        CAST(ARECCLIE AS VARCHAR) as CODICLIE,
        CAST(clie.CADANOME AS VARCHAR) as NOMECLIE,
        CAST(clie.CADACNPJ AS VARCHAR) as CPF_CNPJ,
        CAST(TRIM(clie.CADAESTA) AS VARCHAR) as UF_CLIENTE,
        CONCAT(ARECDOCU, '-P', ARECPARC) as DOCUMENTO,
        ARECPARC as PARCELA,
        CAST(ARECVALO AS NUMERIC(15,2)) as VALOR_TITULO,
        CAST(ARECVALO AS NUMERIC(15,2)) as VALOR_NA_DATA,
        CAST(CASE WHEN ARECFNOT <> ' ' THEN ARECFNOT ELSE ARECTPDC END AS VARCHAR) as FORMPAG,
        ARECEMIS as DATAEMIS
    FROM ARQAREC
    LEFT JOIN ARQCADA as clie ON clie.CADACODI = ARECCLIE
    LEFT JOIN ARQCLIE ON CLIECODI = ARECCLIE
    WHERE ((ARECEMIS <= %s AND ARECORIG NOT IN ('CV1','ENF')) OR (ARECEMIS <= %s AND ARECORIG IN ('CV1','ENF') AND ARECDMOV > %s))
    AND ARECCARD = 0
    AND (SELECT COUNT(1) FROM ARQCREC WHERE CRECEMPE = ARECEMPE AND CRECDOCU = ARECDOCU AND CRECSERI = ARECSERI AND CRECPARC = ARECPARC AND CRECCARD = ARECCARD AND CRECEMIS <= %s) = 0
    AND (SELECT COUNT(1) FROM ARQBREC WHERE BRECEMPE = ARECEMPE AND BRECDOCU = ARECDOCU AND BRECSERI = ARECSERI AND BRECPARC = ARECPARC AND BRECCARD = ARECCARD AND BRECEMIS <= %s) = 0
    -- Fim da nossa query analítica detalhada
) as dados_detalhados
WHERE
    FORMPAG = 'BO'
    AND UPPER(NOMECLIE) <> 'CONSUMIDOR FINAL'
    AND UPPER(NOMECLIE) <> 'A VERIFICAR'
)
SELECT
    cod_cliente,
    cliente,
    documento_cliente,
    uf_cliente,
    DOCUMENTO as documento,
    to_char(DATAEMIS, 'DD/MM/YYYY') as data_emissao,
    PARCELA as parcela,
    vlr_total_vencidos,
    vlr_totalcompras,
    date_part('month', DATAEMIS) as mes_referencia
FROM dados_base
WHERE vlr_total_vencidos > 0
ORDER BY cliente, DATAEMIS, PARCELA;